"""
Medical terminology and abbreviations for radiology studies
"""

# Common radiology abbreviations
ABBREVIATIONS = {
    # Anatomical regions
    'Abd': 'Abdomen',
    'AP': 'Anteroposterior',
    'PA': 'Posteroanterior',
    'Lat': 'Lateral',
    'C-spine': 'Cervical spine',
    'T-spine': 'Thoracic spine',
    'L-spine': 'Lumbar spine',
    'LS spine': 'Lumbosacral spine',
    'KUB': 'Kidney Ureter Bladder',
    'CXR': 'Chest X-ray',
    'Chest PA': 'Chest Posteroanterior',
    'PNS': 'Paranasal sinuses',
    'TMJ': 'Temporomandibular joint',
    'SI': 'Sacroiliac',
    'IVP': 'Intravenous pyelogram',
    'VCUG': 'Voiding cystourethrogram',
    'UGI': 'Upper gastrointestinal',
    'BE': 'Barium enema',
    'ERCP': 'Endoscopic retrograde cholangiopancreatography',
    'MRCP': 'Magnetic resonance cholangiopancreatography',
    'MRA': 'Magnetic resonance angiography',
    'MRV': 'Magnetic resonance venography',
    'CTA': 'Computed tomography angiography',
    'CTV': 'Computed tomography venography',
    'PET': 'Positron emission tomography',
    'SPECT': 'Single-photon emission computed tomography',
    'Rt': 'Right',
    'Lt': 'Left',
    'Bil': 'Bilateral',
    'Bilat': 'Bilateral',
    'UE': 'Upper extremity',
    'LE': 'Lower extremity',
    'w/': 'with',
    'w/o': 'without',
    'C+': 'with contrast',
    'C-': 'without contrast',
}

# Body parts mapping (English to standardized terms)
BODY_PARTS = {
    # Head and Neck
    'head': 'Head',
    'brain': 'Brain',
    'skull': 'Skull',
    'face': 'Face',
    'orbit': 'Orbit',
    'eye': 'Eye',
    'sinus': 'Sinus',
    'paranasal sinus': 'Sinus',
    'pns': 'Sinus',
    'nose': 'Nose',
    'neck': 'Neck',
    'throat': 'Throat',
    'larynx': 'Larynx',
    'pharynx': 'Pharynx',
    'thyroid': 'Thyroid',
    'parotid': 'Parotid',
    'mandible': 'Mandible',
    'maxilla': 'Maxilla',
    'jaw': 'Jaw',
    'tmj': 'Temporomandibular joint',
    'mastoid': 'Mastoid',
    'temporal bone': 'Temporal bone',

    # Spine
    'spine': 'Spine',
    'c-spine': 'Cervical spine',
    'cervical spine': 'Cervical spine',
    't-spine': 'Thoracic spine',
    'thoracic spine': 'Thoracic spine',
    'l-spine': 'Lumbar spine',
    'lumbar spine': 'Lumbar spine',
    'ls spine': 'Lumbosacral spine',
    'lumbosacral spine': 'Lumbosacral spine',
    'sacrum': 'Sacrum',
    'coccyx': 'Coccyx',
    'si joint': 'Sacroiliac joint',
    'sacroiliac': 'Sacroiliac joint',

    # Thorax
    'chest': 'Chest',
    'thorax': 'Chest',
    'lung': 'Lung',
    'heart': 'Heart',
    'mediastinum': 'Mediastinum',
    'rib': 'Rib',
    'sternum': 'Sternum',
    'clavicle': 'Clavicle',
    'scapula': 'Scapula',

    # Abdomen and Pelvis
    'abdomen': 'Abdomen',
    'pelvis': 'Pelvis',
    'hip': 'Hip',
    'liver': 'Liver',
    'gallbladder': 'Gallbladder',
    'pancreas': 'Pancreas',
    'spleen': 'Spleen',
    'kidney': 'Kidney',
    'adrenal': 'Adrenal',
    'ureter': 'Ureter',
    'bladder': 'Bladder',
    'prostate': 'Prostate',
    'uterus': 'Uterus',
    'ovary': 'Ovary',
    'bowel': 'Bowel',
    'colon': 'Colon',
    'rectum': 'Rectum',
    'appendix': 'Appendix',
    'stomach': 'Stomach',
    'duodenum': 'Duodenum',
    'small bowel': 'Small bowel',

    # Upper Extremity
    'shoulder': 'Shoulder',
    'humerus': 'Humerus',
    'elbow': 'Elbow',
    'forearm': 'Forearm',
    'radius': 'Radius',
    'ulna': 'Ulna',
    'wrist': 'Wrist',
    'hand': 'Hand',
    'finger': 'Finger',
    'thumb': 'Thumb',
    'arm': 'Upper extremity',

    # Lower Extremity
    'femur': 'Femur',
    'thigh': 'Thigh',
    'knee': 'Knee',
    'patella': 'Patella',
    'tibia': 'Tibia',
    'fibula': 'Fibula',
    'leg': 'Lower extremity',
    'ankle': 'Ankle',
    'foot': 'Foot',
    'toe': 'Toe',
    'heel': 'Heel',
    'calcaneus': 'Calcaneus',

    # Vascular and Heart
    'heart': 'Heart',
    'cardiac': 'Heart',
    'coronary': 'Coronary artery',
    'coronary artery': 'Coronary artery',
    'coronary arteries': 'Coronary artery',
    'aorta': 'Aorta',
    'carotid': 'Carotid artery',
    'vertebral artery': 'Vertebral artery',
    'pulmonary artery': 'Pulmonary artery',
    'renal artery': 'Renal artery',
    'iliac artery': 'Iliac artery',
    'femoral artery': 'Femoral artery',
    'angiography': 'Angiography',
    'angiogram': 'Angiography',

    # Other
    'whole body': 'Whole body',
    'soft tissue': 'Soft tissue',
    'bone': 'Bone',
    'joint': 'Joint',
}

# Chinese body parts mapping
CHINESE_BODY_PARTS = {
    # 頭頸部
    '頭': 'Head',
    '頭部': 'Head',
    '腦': 'Brain',
    '顱骨': 'Skull',
    '臉': 'Face',
    '面': 'Face',
    '眼': 'Eye',
    '眼窩': 'Orbit',
    '鼻': 'Nose',
    '鼻竇': 'Sinus',
    '副鼻竇': 'Sinus',
    '頸': 'Neck',
    '頸部': 'Neck',
    '喉': 'Larynx',
    '咽': 'Pharynx',
    '甲狀腺': 'Thyroid',
    '下頜': 'Mandible',
    '顎': 'Jaw',

    # 脊椎
    '脊椎': 'Spine',
    '頸椎': 'Cervical spine',
    '胸椎': 'Thoracic spine',
    '腰椎': 'Lumbar spine',
    '薦椎': 'Sacrum',
    '尾椎': 'Coccyx',
    '薦腸關節': 'Sacroiliac joint',

    # 胸部
    '胸': 'Chest',
    '胸部': 'Chest',
    '肺': 'Lung',
    '心': 'Heart',
    '心臟': 'Heart',
    '縱膈': 'Mediastinum',
    '肋骨': 'Rib',
    '胸骨': 'Sternum',
    '鎖骨': 'Clavicle',
    '肩胛骨': 'Scapula',

    # 腹部骨盆
    '腹': 'Abdomen',
    '腹部': 'Abdomen',
    '骨盆': 'Pelvis',
    '髖': 'Hip',
    '髖關節': 'Hip',
    '肝': 'Liver',
    '肝臟': 'Liver',
    '膽': 'Gallbladder',
    '膽囊': 'Gallbladder',
    '胰': 'Pancreas',
    '胰臟': 'Pancreas',
    '脾': 'Spleen',
    '脾臟': 'Spleen',
    '腎': 'Kidney',
    '腎臟': 'Kidney',
    '輸尿管': 'Ureter',
    '膀胱': 'Bladder',
    '前列腺': 'Prostate',
    '攝護腺': 'Prostate',
    '子宮': 'Uterus',
    '卵巢': 'Ovary',
    '腸': 'Bowel',
    '大腸': 'Colon',
    '結腸': 'Colon',
    '直腸': 'Rectum',
    '闌尾': 'Appendix',
    '胃': 'Stomach',
    '十二指腸': 'Duodenum',
    '小腸': 'Small bowel',

    # 上肢
    '肩': 'Shoulder',
    '肩膀': 'Shoulder',
    '肱骨': 'Humerus',
    '上臂': 'Humerus',
    '肘': 'Elbow',
    '前臂': 'Forearm',
    '橈骨': 'Radius',
    '尺骨': 'Ulna',
    '腕': 'Wrist',
    '手腕': 'Wrist',
    '手': 'Hand',
    '手指': 'Finger',
    '拇指': 'Thumb',

    # 下肢
    '股骨': 'Femur',
    '大腿': 'Thigh',
    '膝': 'Knee',
    '膝蓋': 'Knee',
    '髌骨': 'Patella',
    '脛骨': 'Tibia',
    '腓骨': 'Fibula',
    '小腿': 'Lower leg',
    '踝': 'Ankle',
    '腳踝': 'Ankle',
    '足': 'Foot',
    '腳': 'Foot',
    '腳趾': 'Toe',
    '足跟': 'Heel',
    '跟骨': 'Calcaneus',

    # 心血管
    '心': 'Heart',
    '心臟': 'Heart',
    '冠狀動脈': 'Coronary artery',
    '冠脈': 'Coronary artery',
    '主動脈': 'Aorta',
    '頸動脈': 'Carotid artery',
    '肺動脈': 'Pulmonary artery',
    '腎動脈': 'Renal artery',
    '血管攝影': 'Angiography',
    '血管造影': 'Angiography',

    # 其他
    '全身': 'Whole body',
    '軟組織': 'Soft tissue',
    '骨': 'Bone',
    '骨頭': 'Bone',
    '關節': 'Joint',
}

# Laterality keywords
LATERALITY = {
    'right': 'Right',
    'rt': 'Right',
    'r': 'Right',
    'left': 'Left',
    'lt': 'Left',
    'l': 'Left',
    'bilateral': 'Bilateral',
    'bilat': 'Bilateral',
    'bil': 'Bilateral',
    'both': 'Bilateral',
}

# Chinese laterality
CHINESE_LATERALITY = {
    '右': 'Right',
    '左': 'Left',
    '雙': 'Bilateral',
    '雙側': 'Bilateral',
    '兩': 'Bilateral',
    '兩側': 'Bilateral',
}

# Contrast keywords
CONTRAST_KEYWORDS = {
    'with contrast': 'Y',
    'c+': 'Y',
    'enhanced': 'Y',
    'contrast': 'Y',
    'without contrast': 'N',
    'c-': 'N',
    'non-contrast': 'N',
    'unenhanced': 'N',
    'plain': 'N',
}

# Chinese contrast keywords
CHINESE_CONTRAST = {
    '含對比劑': 'Y',
    '有對比劑': 'Y',
    '顯影劑': 'Y',
    '對比劑': 'Y',
    '增強': 'Y',
    '無對比劑': 'N',
    '不含對比劑': 'N',
    '平掃': 'N',
    '加顯影': 'Y',
    '打顯影': 'Y',
    '加藥': 'Y',
    '不加藥': 'N',
    '加打': 'Y',
}

# === EXPANDED Chinese Medical Terminology ===

# Extended Chinese body parts with common clinical terms
CHINESE_BODY_PARTS_EXTENDED = {
    # 頭頸部 - Extended
    '頭': 'Head',
    '頭部': 'Head',
    '腦': 'Brain',
    '腦部': 'Brain',
    '顱內': 'Brain',
    '顱腦': 'Brain',
    '顱': 'Skull',
    '顱骨': 'Skull',
    '臉': 'Face',
    '面': 'Face',
    '面部': 'Face',
    '眼': 'Eye',
    '眼睛': 'Eye',
    '眼窩': 'Orbit',
    '眼眶': 'Orbit',
    '鼻': 'Nose',
    '鼻腔': 'Nose',
    '鼻竇': 'Sinus',
    '副鼻竇': 'Sinus',
    '上頜竇': 'Sinus',
    '篩竇': 'Sinus',
    '蝶竇': 'Sinus',
    '頸': 'Neck',
    '頸部': 'Neck',
    '喉': 'Larynx',
    '喉嚨': 'Larynx',
    '咽': 'Pharynx',
    '咽喉': 'Pharynx',
    '甲狀腺': 'Thyroid',
    '甲状腺': 'Thyroid',
    '下頜': 'Mandible',
    '下頷': 'Mandible',
    '下巴': 'Mandible',
    '顎': 'Jaw',
    '顳骨': 'Temporal bone',
    '乳突': 'Mastoid',
    '耳': 'Ear',
    '內耳': 'Inner ear',
    '中耳': 'Middle ear',
    '顳顎關節': 'Temporomandibular joint',
    '顎關節': 'Temporomandibular joint',

    # 脊椎 - Extended
    '脊椎': 'Spine',
    '脊柱': 'Spine',
    '背': 'Spine',
    '頸椎': 'Cervical spine',
    '頸脊椎': 'Cervical spine',
    'C1': 'Cervical spine',
    'C2': 'Cervical spine',
    'C3': 'Cervical spine',
    'C4': 'Cervical spine',
    'C5': 'Cervical spine',
    'C6': 'Cervical spine',
    'C7': 'Cervical spine',
    '胸椎': 'Thoracic spine',
    '背椎': 'Thoracic spine',
    'T1': 'Thoracic spine',
    'T12': 'Thoracic spine',
    '腰椎': 'Lumbar spine',
    '腰脊椎': 'Lumbar spine',
    '腰': 'Lumbar spine',
    'L1': 'Lumbar spine',
    'L2': 'Lumbar spine',
    'L3': 'Lumbar spine',
    'L4': 'Lumbar spine',
    'L5': 'Lumbar spine',
    '腰薦椎': 'Lumbosacral spine',
    '腰骶椎': 'Lumbosacral spine',
    '薦椎': 'Sacrum',
    '骶椎': 'Sacrum',
    '尾椎': 'Coccyx',
    '尾骨': 'Coccyx',
    '薦腸關節': 'Sacroiliac joint',
    '薦髂關節': 'Sacroiliac joint',
    '骶髂關節': 'Sacroiliac joint',

    # 胸部 - Extended
    '胸': 'Chest',
    '胸部': 'Chest',
    '胸腔': 'Chest',
    '肺': 'Lung',
    '肺部': 'Lung',
    '雙肺': 'Lung',
    '心': 'Heart',
    '心臟': 'Heart',
    '心藏': 'Heart',
    '縱膈': 'Mediastinum',
    '縱隔': 'Mediastinum',
    '肋骨': 'Rib',
    '肋': 'Rib',
    '胸骨': 'Sternum',
    '鎖骨': 'Clavicle',
    '肩胛骨': 'Scapula',
    '肩胛': 'Scapula',
    '乳房': 'Breast',
    '乳腺': 'Breast',

    # 腹部骨盆 - Extended
    '腹': 'Abdomen',
    '腹部': 'Abdomen',
    '上腹': 'Abdomen',
    '下腹': 'Abdomen',
    '腹腔': 'Abdomen',
    '骨盆': 'Pelvis',
    '骨盤': 'Pelvis',
    '盆腔': 'Pelvis',
    '髖': 'Hip',
    '髖部': 'Hip',
    '髖關節': 'Hip',
    '股骨頭': 'Hip',
    '肝': 'Liver',
    '肝臟': 'Liver',
    '肝藏': 'Liver',
    '膽': 'Gallbladder',
    '膽囊': 'Gallbladder',
    '膽管': 'Bile duct',
    '總膽管': 'Common bile duct',
    '胰': 'Pancreas',
    '胰臟': 'Pancreas',
    '胰腺': 'Pancreas',
    '脾': 'Spleen',
    '脾臟': 'Spleen',
    '脾藏': 'Spleen',
    '腎': 'Kidney',
    '腎臟': 'Kidney',
    '腎藏': 'Kidney',
    '雙腎': 'Kidney',
    '腎上腺': 'Adrenal',
    '副腎': 'Adrenal',
    '輸尿管': 'Ureter',
    '膀胱': 'Bladder',
    '前列腺': 'Prostate',
    '攝護腺': 'Prostate',
    '子宮': 'Uterus',
    '卵巢': 'Ovary',
    '腸': 'Bowel',
    '大腸': 'Colon',
    '結腸': 'Colon',
    '直腸': 'Rectum',
    '闘尾': 'Appendix',
    '盲腸': 'Appendix',
    '闌尾': 'Appendix',
    '胃': 'Stomach',
    '十二指腸': 'Duodenum',
    '小腸': 'Small bowel',

    # 上肢 - Extended
    '肩': 'Shoulder',
    '肩膀': 'Shoulder',
    '肩部': 'Shoulder',
    '肩關節': 'Shoulder',
    '肱骨': 'Humerus',
    '上臂': 'Humerus',
    '肘': 'Elbow',
    '肘部': 'Elbow',
    '肘關節': 'Elbow',
    '前臂': 'Forearm',
    '橈骨': 'Radius',
    '尺骨': 'Ulna',
    '腕': 'Wrist',
    '手腕': 'Wrist',
    '腕關節': 'Wrist',
    '手': 'Hand',
    '手部': 'Hand',
    '手掌': 'Hand',
    '手指': 'Finger',
    '拇指': 'Thumb',
    '指': 'Finger',

    # 下肢 - Extended
    '股骨': 'Femur',
    '大腿': 'Thigh',
    '大腿骨': 'Femur',
    '膝': 'Knee',
    '膝蓋': 'Knee',
    '膝關節': 'Knee',
    '膝部': 'Knee',
    '髕骨': 'Patella',
    '髌骨': 'Patella',
    '脛骨': 'Tibia',
    '腓骨': 'Fibula',
    '小腿': 'Lower leg',
    '踝': 'Ankle',
    '腳踝': 'Ankle',
    '踝關節': 'Ankle',
    '足': 'Foot',
    '腳': 'Foot',
    '足部': 'Foot',
    '腳趾': 'Toe',
    '足跟': 'Heel',
    '跟骨': 'Calcaneus',

    # 心血管 - Extended
    '冠狀動脈': 'Coronary artery',
    '冠脈': 'Coronary artery',
    '冠動脈': 'Coronary artery',
    '主動脈': 'Aorta',
    '大動脈': 'Aorta',
    '頸動脈': 'Carotid artery',
    '頸部動脈': 'Carotid artery',
    '椎動脈': 'Vertebral artery',
    '肺動脈': 'Pulmonary artery',
    '腎動脈': 'Renal artery',
    '髂動脈': 'Iliac artery',
    '股動脈': 'Femoral artery',
    '血管攝影': 'Angiography',
    '血管造影': 'Angiography',
    '動脈': 'Artery',
    '靜脈': 'Vein',

    # 其他
    '全身': 'Whole body',
    '軟組織': 'Soft tissue',
    '骨': 'Bone',
    '骨頭': 'Bone',
    '關節': 'Joint',
    '淋巴': 'Lymph node',
    '淋巴結': 'Lymph node',
    '陰囊': 'Scrotum',
    '睪丸': 'Testis',
}

# Extended Chinese modality terms
CHINESE_MODALITY = {
    # X光/普通放射
    'X光': 'CR',
    'X-光': 'CR',
    '艾克斯光': 'CR',
    '普通攝影': 'CR',
    '平片': 'CR',
    '正面': 'CR',
    '側面': 'CR',
    '正側面': 'CR',
    '站立位': 'CR',
    '臥位': 'CR',

    # CT
    '電腦斷層': 'CT',
    '斷層掃描': 'CT',
    '斷層': 'CT',
    '電腦斷層掃描': 'CT',
    'CT掃描': 'CT',
    '低劑量電腦斷層': 'CT',
    'LDCT': 'CT',

    # MRI
    '磁振造影': 'MR',
    '核磁共振': 'MR',
    '核磁': 'MR',
    'MRI': 'MR',
    '磁共振': 'MR',
    'MR': 'MR',

    # 超音波
    '超音波': 'US',
    '超聲波': 'US',
    '超聲': 'US',
    '都卜勒': 'US',
    '彩超': 'US',
    'B超': 'US',

    # 透視/螢光攝影
    '透視': 'RF',
    '螢光攝影': 'RF',
    '螢光': 'RF',
    '動態攝影': 'RF',

    # 血管攝影
    '血管攝影': 'XA',
    '血管造影': 'XA',
    '導管攝影': 'XA',
    '心導管': 'XA',
    'DSA': 'XA',

    # 骨密度
    '骨密度': 'BMD',
    '骨質密度': 'BMD',
    'DXA': 'BMD',
    'DEXA': 'BMD',

    # 乳房攝影
    '乳房攝影': 'MG',
    '乳房X光': 'MG',
    '乳攝': 'MG',
    '乳篩': 'MG',

    # 血管CT/MRI
    'CTA': 'CT',
    '電腦斷層血管攝影': 'CT',
    'MRA': 'MR',
    '磁振血管攝影': 'MR',
    'MRV': 'MR',
}

# Extended Chinese abbreviations for radiology
CHINESE_ABBREVIATIONS = {
    # 檢查名稱縮寫
    'CXR': 'Chest X-ray',
    '胸X': 'Chest X-ray',
    'KUB': 'Kidney Ureter Bladder',
    '腹X': 'Abdomen X-ray',
    'HRCT': 'High-resolution CT',
    '高解析度CT': 'High-resolution CT',
    'LDCT': 'Low-dose CT',
    '低劑量CT': 'Low-dose CT',

    # 位置縮寫
    'AP': 'Anteroposterior',
    '前後位': 'Anteroposterior',
    'PA': 'Posteroanterior',
    '後前位': 'Posteroanterior',
    'Lat': 'Lateral',
    '側位': 'Lateral',
    '正面': 'Anteroposterior',
    '正側': 'AP and Lateral',
}

# Update the main CHINESE_BODY_PARTS with extended version
CHINESE_BODY_PARTS.update(CHINESE_BODY_PARTS_EXTENDED)
