"""
Medical terminology and abbreviations for radiology studies
"""

# Common radiology abbreviations
ABBREVIATIONS = {
    # Anatomical regions
    'Abd': 'Abdomen',
    'AP': 'Anteroposterior',
    'PA': 'Posteroanterior',
    'Lat': 'Lateral',
    'C-spine': 'Cervical spine',
    'T-spine': 'Thoracic spine',
    'L-spine': 'Lumbar spine',
    'LS spine': 'Lumbosacral spine',
    'KUB': 'Kidney Ureter Bladder',
    'CXR': 'Chest X-ray',
    'Chest PA': 'Chest Posteroanterior',
    'PNS': 'Paranasal sinuses',
    'TMJ': 'Temporomandibular joint',
    'SI': 'Sacroiliac',
    'IVP': 'Intravenous pyelogram',
    'VCUG': 'Voiding cystourethrogram',
    'UGI': 'Upper gastrointestinal',
    'BE': 'Barium enema',
    'ERCP': 'Endoscopic retrograde cholangiopancreatography',
    'MRCP': 'Magnetic resonance cholangiopancreatography',
    'MRA': 'Magnetic resonance angiography',
    'MRV': 'Magnetic resonance venography',
    'CTA': 'Computed tomography angiography',
    'CTV': 'Computed tomography venography',
    'PET': 'Positron emission tomography',
    'SPECT': 'Single-photon emission computed tomography',
    'Rt': 'Right',
    'Lt': 'Left',
    'Bil': 'Bilateral',
    'Bilat': 'Bilateral',
    'UE': 'Upper extremity',
    'LE': 'Lower extremity',
    'w/': 'with',
    'w/o': 'without',
    'C+': 'with contrast',
    'C-': 'without contrast',
}

# Body parts mapping (English to standardized terms)
BODY_PARTS = {
    # Head and Neck
    'head': 'Head',
    'brain': 'Brain',
    'skull': 'Skull',
    'face': 'Face',
    'orbit': 'Orbit',
    'eye': 'Eye',
    'sinus': 'Sinus',
    'paranasal sinus': 'Sinus',
    'pns': 'Sinus',
    'nose': 'Nose',
    'neck': 'Neck',
    'throat': 'Throat',
    'larynx': 'Larynx',
    'pharynx': 'Pharynx',
    'thyroid': 'Thyroid',
    'parotid': 'Parotid',
    'mandible': 'Mandible',
    'maxilla': 'Maxilla',
    'jaw': 'Jaw',
    'tmj': 'Temporomandibular joint',
    'mastoid': 'Mastoid',
    'temporal bone': 'Temporal bone',

    # Spine
    'spine': 'Spine',
    'c-spine': 'Cervical spine',
    'cervical spine': 'Cervical spine',
    't-spine': 'Thoracic spine',
    'thoracic spine': 'Thoracic spine',
    'l-spine': 'Lumbar spine',
    'lumbar spine': 'Lumbar spine',
    'ls spine': 'Lumbosacral spine',
    'lumbosacral spine': 'Lumbosacral spine',
    'sacrum': 'Sacrum',
    'coccyx': 'Coccyx',
    'si joint': 'Sacroiliac joint',
    'sacroiliac': 'Sacroiliac joint',

    # Thorax
    'chest': 'Chest',
    'thorax': 'Chest',
    'lung': 'Lung',
    'heart': 'Heart',
    'mediastinum': 'Mediastinum',
    'rib': 'Rib',
    'sternum': 'Sternum',
    'clavicle': 'Clavicle',
    'scapula': 'Scapula',

    # Abdomen and Pelvis
    'abdomen': 'Abdomen',
    'pelvis': 'Pelvis',
    'hip': 'Hip',
    'liver': 'Liver',
    'gallbladder': 'Gallbladder',
    'pancreas': 'Pancreas',
    'spleen': 'Spleen',
    'kidney': 'Kidney',
    'adrenal': 'Adrenal',
    'ureter': 'Ureter',
    'bladder': 'Bladder',
    'prostate': 'Prostate',
    'uterus': 'Uterus',
    'ovary': 'Ovary',
    'bowel': 'Bowel',
    'colon': 'Colon',
    'rectum': 'Rectum',
    'appendix': 'Appendix',
    'stomach': 'Stomach',
    'duodenum': 'Duodenum',
    'small bowel': 'Small bowel',

    # Upper Extremity
    'shoulder': 'Shoulder',
    'humerus': 'Humerus',
    'elbow': 'Elbow',
    'forearm': 'Forearm',
    'radius': 'Radius',
    'ulna': 'Ulna',
    'wrist': 'Wrist',
    'hand': 'Hand',
    'finger': 'Finger',
    'thumb': 'Thumb',
    'arm': 'Upper extremity',

    # Lower Extremity
    'femur': 'Femur',
    'thigh': 'Thigh',
    'knee': 'Knee',
    'patella': 'Patella',
    'tibia': 'Tibia',
    'fibula': 'Fibula',
    'leg': 'Lower extremity',
    'ankle': 'Ankle',
    'foot': 'Foot',
    'toe': 'Toe',
    'heel': 'Heel',
    'calcaneus': 'Calcaneus',

    # Vascular and Heart
    'heart': 'Heart',
    'cardiac': 'Heart',
    'coronary': 'Coronary artery',
    'coronary artery': 'Coronary artery',
    'coronary arteries': 'Coronary artery',
    'aorta': 'Aorta',
    'carotid': 'Carotid artery',
    'vertebral artery': 'Vertebral artery',
    'pulmonary artery': 'Pulmonary artery',
    'renal artery': 'Renal artery',
    'iliac artery': 'Iliac artery',
    'femoral artery': 'Femoral artery',
    'angiography': 'Angiography',
    'angiogram': 'Angiography',

    # Other
    'whole body': 'Whole body',
    'soft tissue': 'Soft tissue',
    'bone': 'Bone',
    'joint': 'Joint',
}

# Chinese body parts mapping
CHINESE_BODY_PARTS = {
    # 頭頸部
    '頭': 'Head',
    '頭部': 'Head',
    '腦': 'Brain',
    '顱骨': 'Skull',
    '臉': 'Face',
    '面': 'Face',
    '眼': 'Eye',
    '眼窩': 'Orbit',
    '鼻': 'Nose',
    '鼻竇': 'Sinus',
    '副鼻竇': 'Sinus',
    '頸': 'Neck',
    '頸部': 'Neck',
    '喉': 'Larynx',
    '咽': 'Pharynx',
    '甲狀腺': 'Thyroid',
    '下頜': 'Mandible',
    '顎': 'Jaw',

    # 脊椎
    '脊椎': 'Spine',
    '頸椎': 'Cervical spine',
    '胸椎': 'Thoracic spine',
    '腰椎': 'Lumbar spine',
    '薦椎': 'Sacrum',
    '尾椎': 'Coccyx',
    '薦腸關節': 'Sacroiliac joint',

    # 胸部
    '胸': 'Chest',
    '胸部': 'Chest',
    '肺': 'Lung',
    '心': 'Heart',
    '心臟': 'Heart',
    '縱膈': 'Mediastinum',
    '肋骨': 'Rib',
    '胸骨': 'Sternum',
    '鎖骨': 'Clavicle',
    '肩胛骨': 'Scapula',

    # 腹部骨盆
    '腹': 'Abdomen',
    '腹部': 'Abdomen',
    '骨盆': 'Pelvis',
    '髖': 'Hip',
    '髖關節': 'Hip',
    '肝': 'Liver',
    '肝臟': 'Liver',
    '膽': 'Gallbladder',
    '膽囊': 'Gallbladder',
    '胰': 'Pancreas',
    '胰臟': 'Pancreas',
    '脾': 'Spleen',
    '脾臟': 'Spleen',
    '腎': 'Kidney',
    '腎臟': 'Kidney',
    '輸尿管': 'Ureter',
    '膀胱': 'Bladder',
    '前列腺': 'Prostate',
    '攝護腺': 'Prostate',
    '子宮': 'Uterus',
    '卵巢': 'Ovary',
    '腸': 'Bowel',
    '大腸': 'Colon',
    '結腸': 'Colon',
    '直腸': 'Rectum',
    '闌尾': 'Appendix',
    '胃': 'Stomach',
    '十二指腸': 'Duodenum',
    '小腸': 'Small bowel',

    # 上肢
    '肩': 'Shoulder',
    '肩膀': 'Shoulder',
    '肱骨': 'Humerus',
    '上臂': 'Humerus',
    '肘': 'Elbow',
    '前臂': 'Forearm',
    '橈骨': 'Radius',
    '尺骨': 'Ulna',
    '腕': 'Wrist',
    '手腕': 'Wrist',
    '手': 'Hand',
    '手指': 'Finger',
    '拇指': 'Thumb',

    # 下肢
    '股骨': 'Femur',
    '大腿': 'Thigh',
    '膝': 'Knee',
    '膝蓋': 'Knee',
    '髌骨': 'Patella',
    '脛骨': 'Tibia',
    '腓骨': 'Fibula',
    '小腿': 'Lower leg',
    '踝': 'Ankle',
    '腳踝': 'Ankle',
    '足': 'Foot',
    '腳': 'Foot',
    '腳趾': 'Toe',
    '足跟': 'Heel',
    '跟骨': 'Calcaneus',

    # 心血管
    '心': 'Heart',
    '心臟': 'Heart',
    '冠狀動脈': 'Coronary artery',
    '冠脈': 'Coronary artery',
    '主動脈': 'Aorta',
    '頸動脈': 'Carotid artery',
    '肺動脈': 'Pulmonary artery',
    '腎動脈': 'Renal artery',
    '血管攝影': 'Angiography',
    '血管造影': 'Angiography',

    # 其他
    '全身': 'Whole body',
    '軟組織': 'Soft tissue',
    '骨': 'Bone',
    '骨頭': 'Bone',
    '關節': 'Joint',
}

# Laterality keywords
LATERALITY = {
    'right': 'Right',
    'rt': 'Right',
    'r': 'Right',
    'left': 'Left',
    'lt': 'Left',
    'l': 'Left',
    'bilateral': 'Bilateral',
    'bilat': 'Bilateral',
    'bil': 'Bilateral',
    'both': 'Bilateral',
}

# Chinese laterality
CHINESE_LATERALITY = {
    '右': 'Right',
    '左': 'Left',
    '雙': 'Bilateral',
    '雙側': 'Bilateral',
    '兩': 'Bilateral',
    '兩側': 'Bilateral',
}

# Contrast keywords
CONTRAST_KEYWORDS = {
    'with contrast': 'Y',
    'c+': 'Y',
    'enhanced': 'Y',
    'contrast': 'Y',
    'without contrast': 'N',
    'c-': 'N',
    'non-contrast': 'N',
    'unenhanced': 'N',
    'plain': 'N',
}

# Chinese contrast keywords
CHINESE_CONTRAST = {
    '含對比劑': 'Y',
    '有對比劑': 'Y',
    '顯影劑': 'Y',
    '對比劑': 'Y',
    '增強': 'Y',
    '無對比劑': 'N',
    '不含對比劑': 'N',
    '平掃': 'N',
}
